services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    hostname: traefik
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_API_KEY=${CF_API_KEY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./config:/config:ro
      - ./acme.json:/acme.json

  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    hostname: homarr
    networks: 
      - proxy
    volumes:
      - ./../homarr/datadata:/appdata 
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SECRET_ENCRYPTION_KEY=${SECRET_ENCRYPTION_KEY}
      - ENABLE_DNS_CACHING=true
      - BASE_URL=https://home.${DOMAIN}
      - NEXTAUTH_URL=https://home.${DOMAIN}
      - AUTH_PROVIDERS=oidc,credentials
      - AUTH_OIDC_CLIENT_ID=${HOMARR_OIDC_CLIENT_ID}
      - AUTH_OIDC_CLIENT_SECRET=${HOMARR_OIDC_CLIENT_SECRET}
      - AUTH_OIDC_ISSUER=https://auth.${DOMAIN}/application/o/homarr/
      - AUTH_OIDC_URI=https://auth.${DOMAIN}/application/o/authorize/
      - AUTH_OIDC_CLIENT_NAME=homarr
      - AUTH_OIDC_SCOPE_OVERWRITE=openid email profile groups
      - AUTH_LOGOUT_REDIRECT_URL=https://auth.${DOMAIN}/application/o/homarr/end-session/
      - AUTH_OIDC_GROUPS_ATTRIBUTE=groups
      - AUTH_OIDC_AUTO_LOGIN=true #To sign in with Authentik automatically

  technitium:
    container_name: dns-sec
    hostname: technitium
    image: docker.io/technitium/dns-server:latest
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65535 #remove when using "host" network mode
    networks:
      - proxy
    ports:
      - 53:53/udp #DNS service
      - 53:53/tcp #DNS service
      - 53443:53443 #cluster
    environment:
      - DNS_SERVER_ADMIN_PASSWORD=password
      - DNS_SERVER_OPTIONAL_PROTOCOL_DNS_OVER_HTTP=true #Enables DNS server optional protocol DNS-over-HTTP on TCP port 8053 to be used with a TLS terminating reverse proxy like nginx.
      - DNS_SERVER_RECURSION=UseSpecifiedNetworkACL  #Recursion options: Allow, Deny, AllowOnlyForPrivateNetworks, UseSpecifiedNetworkACL.
      - DNS_SERVER_RECURSION_NETWORK_ACL=192.168.7.1/32, 192.168.10.1/32, 10.0.100.1/32, 10.0.20.1/32, 10.0.14.1/32, 172.16.30.1/32, 10.0.42.1/32 
      - DNS_SERVER_LOG_USING_LOCAL_TIME=true #Enable this option to use local time instead of UTC for logging.
      - DNS_SERVER_LOG_FOLDER_PATH=/var/log/technitium/dns #The folder path on the server where the log files should be saved.
      - DNS_SERVER_LOG_MAX_LOG_FILE_DAYS=7 #Max number of days to keep the log files. Log files older than the specified number of days will be deleted automatically. Set 0 to disable auto delete.
      - DNS_SERVER_STATS_ENABLE_IN_MEMORY_STATS=true #This option will enable in-memory stats and only Last Hour data will be available on Dashboard. No stats data will be stored on disk.
      - DNS_SERVER_STATS_MAX_STAT_FILE_DAYS=7 #Max number of days to keep the dashboard stats. Stat files older than the specified number of days will be deleted automatically. Set 0 to disable auto delete.
    volumes:
      - ${config:-~/config}/technitium:/etc/dns
      - ${config:-~/config}/technitium/logs:/var/log/technitium/dns

  tunnel:
    container_name: tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run

networks:
  proxy:
    driver: bridge