dns:
  hosts:
    artemis:
      ansible_host: 192.168.7.11
      ansible_user: pi
      ansible_python_interpreter: /usr/bin/python3
      compose_dirs:
        - docker-server/primary

    apollo:
      ansible_host: 192.168.7.10
      ansible_user: pi
      ansible_python_interpreter: /usr/bin/python3
      compose_dirs:
        - docker-server/secondary

proxmox:
  hosts:
    hephaestus:
      ansible_host: 10.0.14.2
      ansible_user: root

lxc:
  hosts:    
    mqtt:
      ansible_host: 192.168.10.4
      ansible_user: root

virtual:
  hosts:
    hestia:
      ansible_host: 10.0.14.4
      ansible_user: ubuntu
      compose_dirs:
        - docker-server/base
        - docker-server/downloads
        - docker-server/hardware
        - docker-server/nvr
        - docker-server/image

self:
  hosts:
    localhost:
      ansible_connection: local

init:
  hosts:
    new:
      ansible_host: 192.168.7.97