services:
  plex:
    image: 'lscr.io/linuxserver/plex'
    container_name: plex
    network_mode: host
    privileged: true
    restart: unless-stopped
    environment:
      - PGID=${PGID:-1000}
      - PUID=${PUID:-1000}
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - ${config:-~/config}/plex:/config
      - ${tv}:/tv
      - ${movies}:/movies
      - ${config:-~/config}/transcode/plex:/transcode

  tdarr:
    container_name: tdarr
    image: 'ghcr.io/haveagitgat/tdarr:latest'
    restart: unless-stopped
    networks: 
      - docker
    privileged: true
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
      - 8267:8267 # Internal node port
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Australia/Melbourne}
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - nodeID=MyInternalNode
      - nodeIP=0.0.0.0
      - nodePort=8267
    volumes:
      - ${config:-~/config}/tdarr/server:/app/server
      - ${config:-~/config}/tdarr/config:/app/configs
      - ${config:-~/config}/tdarr/logs:/app/logs
      - ${config:-~/config}/transcode/tdarr:/temp
      - ${tv}:/tv
      - ${movies}:/movies
      - ${videos}:/videos
      
networks:
  docker:
    driver: bridge