http:
  routers:
    traefik:
      entryPoints:
        - https
      rule: Host(`traefik.lontiotlabs.au`)
      middlewares:
        - secured@file
      tls:
        certResolver: cloudflare
        domains:
          - main: lontiotlabs.au
            sans:
              - '*.lontiotlabs.au'
          - sans:
              - '*.camera.lontiotlabs.au'
          - sans:
              - '*.iot.lontiotlabs.au'
          - sans:
              - '*.virtual.lontiotlabs.au'
      service: api@internal

    homarr:
      entryPoints:
        - https
      rule: Host(`home.lontiotlabs.au`)
      middlewares:
        - secured@file
      tls: {}
      service: homarr

    technitium:
      entryPoints:
        - https
      rule: Host(`dns-sec.lontiotlabs.au`)
      middlewares:
        - secured@file
      tls: {}
      service: technitium-web

    technitium-doh:
      entryPoints:
        - https
      rule: Host(`dns-sec.lontiotlabs.au`) && PathPrefix(`/dns-query`)
      priority: 100
      middlewares:
        - secured@file
      tls: {}
      service: technitium-doh

  services:
    homarr:
      loadBalancer:
        servers:
          - url: http://homarr:7575
        passHostHeader: true
    technitium:
      loadBalancer:
        servers:
          - url: http://technitium:5380
    technitium-doh:
      loadBalancer:
        servers:
          - url: http://technitium:80
    traefik:
      loadBalancer:
        servers:
          - url: http://traefik:80