http:
  routers:
    traefik-http:
      entryPoints:
        - http
      rule: Host(`traefik.lontiotlabs.au`)
      middlewares:
        - https-redirectscheme@file
      service: api@internal

    traefik:
      entryPoints:
        - https
      rule: Host(`traefik.lontiotlabs.au`)
      middlewares:
        - secured@file
      tls:
        certResolver: cloudflare
        domains:
          - main: lontiotlabs.au
            sans:
              - '*.lontiotlabs.au'
          - sans:
              - '*.camera.lontiotlabs.au'
          - sans:
              - '*.iot.lontiotlabs.au'
          - sans:
              - '*.virtual.lontiotlabs.au'
      service: api@internal

    homarr:
      entryPoints:
        - https
      rule: Host(`home.lontiotlabs.au`)
      middlewares:
        - secured@file
      tls: {}
      service: homarr

    technitium-http:
      entryPoints:
        - http
      rule: Host(`dns-tech.lontiotlabs.au`)
      service: technitium-web

    technitium-https:
      entryPoints:
        - https
      rule: Host(`dns-tech.lontiotlabs.au`)
      middlewares:
        - secured@file
      tls:
        certResolver: cloudflare
      service: technitium-web

    technitium-doh:
      entryPoints:
        - https
      rule: Host(`dns-tech.lontiotlabs.au`) && PathPrefix(`/dns-query`)
      priority: 100
      tls:
        certResolver: cloudflare
      service: technitium-doh

  services:
    homarr:
      loadBalancer:
        servers:
          - url: http://homarr:7575
        passHostHeader: true

    technitium-web:
      loadBalancer:
        servers:
          - url: http://technitium:5380
        passHostHeader: true

    technitium-doh:
      loadBalancer:
        servers:
          - url: http://technitium:80
        passHostHeader: true

    traefik:
      loadBalancer:
        servers:
          - url: http://traefik:80