- name: Add log2ram GPG key
  ansible.builtin.apt_key:
    url: https://azlux.fr/repo.gpg
    state: present
  tags: log2ram

- name: add log2ram repo
  ansible.builtin.apt_repository:
    repo: deb http://packages.azlux.fr/debian/ buster main
    state: present
    update_cache: yes
  tags: log2ram

- name: install log2ram
  ansible.builtin.apt:
    pkg:
      - log2ram
    state: present
    update_cache: yes
  register: pkg
  notify: Restart log2ram    
  tags: log2ram

- name: Set config options
  become: true
  lineinfile:
    path: /etc/log2ram.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: true
  loop:
    - { regexp: "^SIZE=(.*)$", line: "SIZE={{ log2ram_size }}" }
    - {
        regexp: "^PATH_DISK=(.*)$",
        line: 'PATH_DISK="/var/log"',
      }
    - { regexp: "^ZL2R=(.*)$", line: "ZL2R={{ log2ram_use_z2lr|lower }}" }
    - { regexp: "^COMP_ALG=(.*)$", line: "COMP_ALG={{ log2ram_comp_alg }}" }
    - {
        regexp: "^LOG_DISK_SIZE=(.*)$",
        line: "LOG_DISK_SIZE={{ log2ram_log_disk_size }}",
      }
  tags: log2ram
  notify: Restart log2ram