- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
  tags:
    - always

- name: Copy SSH config
  ansible.builtin.copy:
    src: sshd_config
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    dest: /etc/ssh/sshd_config
  tags:
    - always

- name: Copy SSH key
  ansible.builtin.copy:
    src: '~/.ssh/id_ed25519'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
    dest: /home/{{ ansible_user }}/.ssh/id_ed25519
  tags:
    - always

- name: Copy SSH Pub key
  ansible.builtin.copy:
    src: '~/.ssh/id_ed25519.pub'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
    dest: /home/{{ ansible_user }}/.ssh/id_ed25519.pub
  tags:
    - always

- name: Stop and Start ssh
  ansible.builtin.service:
      name: ssh
      state: restarted
  tags:
    - always