- name: Configure new user 
  hosts: init
  user: root
  vars_prompt:
  - name: "new_user"    
    prompt: "Enter a new user"     
    private: false

  - name: "user_password"    
    prompt: "Enter a password for the user"    
    private: true
    encrypt: "md5_crypt" #need to have python-passlib installed in local machine before we can use it    
    confirm: true
    salt_size: 7
    
  - name: "hostname"    
    prompt: "Enter a new hostname"
    private: false    

  roles:
    - role: user
      vars:
        new_user: {{ new_user }}
    - sudo 
    - hostname

- name: Initalise
  hosts: 192.168.7.51
  become: true
  roles:
    - whoami
    - sudo
    - updates   #restart
    - ssh       
    - apt       #vm, docker
    - vscode        
    - git       #init
    - docker    
    - role: nfs
      vars:
        nas: 10.0.14.14
    - role: ufw       #DNS, torrent, plex, nextcloud  
      vars: 
        proxy_int: 192.168.7.10
        proxy_ext: 192.168.7.11

#ansible-playbook playbooks/init.yaml -u ubuntu -k -t docker,vm