- hosts: dns, proxmox, lxc, virtual, self
  become: true
  roles:
    - updates   #restart
    # - role: git    
    #   when:
    #     - "'proxmox' not in group_names"
    #     - "'lxc' not in group_names"