- hosts: dns, proxmox, lxc, virtual, self
  become: true
  roles:
    - updates   #restart
    - role: git
      when: >
        'dns' in group_names 
        or 
        'virtual' in group_names
    - role: docker-images
      when: >
        'dns' in group_names 
        or
        'virtual' in group_names