- hosts: pihole, docker
  become: true
  roles:
    - updates   #restart
    - pihole-update
    - git
    - nvidia
    - role: nvidia-driver
      when: "inventory_hostname == 'dionysus' and 'failed' in results.stdout|lower"
    - role: watchtower    
      when: "inventory_hostname != 'demeter'"