- hosts: artemis
  become: true
  roles:
    - role: vlans
      vars:
        vlan_dict:
            #IOT Vlan
          - vlan: 10
            ip_address: 192.168.10.10/24
            router: 192.168.10.1
            #Work Vlan
          - vlan: 20
            ip_address: 10.0.20.10/28
            router: 10.0.20.1
            #Virtual Vlan
          - vlan: 14
            ip_address: 10.0.14.10/28
            router: 10.0.14.1
            #Media Vlan
          - vlan: 30
            ip_address: 192.168.30.10/24
            router: 192.168.30.1

# - hosts: apollo uses network manager
#   become: true
#   roles:
#     - role: vlans
#       vars:
#         vlan_dict:
#             #IOT Vlan
#           - vlan: 10
#             ip_address: 192.168.10.11/24
#             router: 192.168.10.1
#             #Work Vlan
#           - vlan: 20
#             ip_address: 10.0.20.11/28
#             router: 10.0.20.1
#             #Virtual Vlan
#           - vlan: 14
#             ip_address: 10.0.14.11/28
#             router: 10.0.14.1
#             #Media Vlan
#           - vlan: 30
#             ip_address: 192.168.30.11/24
#             router: 192.168.30.1