api:
  dashboard: true
  debug: true

accessLog:
  format: json
  filters:
    statusCodes:
      - "200"
      - "400-404"
      - "500-503"

log:
  level: INFO

entryPoints:
  http:
    address: ":80"
    http:
      middlewares:
        - secured@file
        - https-redirectscheme@file
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
    http:
      middlewares:
        - secured@file

serversTransport:
  insecureSkipVerify: true

providers:
  file:
    directory: /config
    watch: true
    
certificatesResolvers:
  cloudflare:
    acme:
      email: alex_lont@hotmail.com
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"