services:
  speedtest:
    image: henrywhitaker3/speedtest-tracker:latest
    container_name: speedtest
    networks:
      - docker
    restart: unless-stopped
    ports:
      - 8765:80
    environment:
      - TZ=${TZ:-Australia/Melbourne}
      - PGID=${PGID:-1000}
      - PUID=${PUID:-1000}
      - OOKLA_EULA_GDPR=true
    volumes:
      - ${config:-~/config}/speedtest:/config

  flatnotes:
    container_name: flatnotes
    image: dullage/flatnotes:latest
    networks:
      - docker
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      FLATNOTES_AUTH_TYPE: "None"
    volumes:
      - ${config:-~/config}/flatnotes:/data
    ports:
      - 8000:8080
    restart: unless-stopped
    
  tududi:
    container_name: tududi
    image: chrisvel/tududi:latest
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - 3002:3002
    environment:
      - TUDUDI_USER_NAME=admin 
      - TUDUDI_USER_EMAIL=${CF_API_EMAIL}
      - TUDUDI_USER_PASSWORD=${MYSQL_PASSWORD}
      - TUDUDI_SESSION_SECRET=${SECRET_ENCRYPTION_KEY}
    volumes:
      - ${config}/tududi/db:/app/backend/db
      - ${config}/tududi/uploads:/app/backend/uploads

  organizr:
    container_name: organizr
    hostname: organizr
    image: ghcr.io/organizr/organizr:latest
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - 8881:80
    volumes:
      - ${config:-~/config}/organizr:/config
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Australia/Melbourne}
      - branch=v2-develop
    dns:
      - 192.168.7.10
      - 192.168.7.11

  dumbassets:
    container_name: dumbassets
    image: dumbwareio/dumbassets:latest
    restart: unless-stopped
    networks:
      - docker
    ports: 
      - 3000:3000
    volumes:
      - ${config:-~/config}/dumbasset:/app/data
    environment:
      NODE_ENV: production
      DEBUG: False
      SITE_TITLE: Assets
      TZ: ${TZ:-Australia/Melbourne}

networks:
  docker:
    driver: bridge